-- ============================================================
-- CLUBES DE LECTURA - BASE DE DATOS TRANSACCIONAL (NUEVO MODELO)
-- Archivo: 01_secuencias.sql
-- Descripcion: Creacion de todas las secuencias
-- Prefijo: CASJ_
-- MBD: Oracle
-- ============================================================

-- ============================================================
-- LIMPIEZA PREVIA (DROP si existen)
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_PAISES';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_CIUDADES';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_INSTITUCIONES';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_CLUB_LECTOR';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_IDIOMAS';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_GRUPOS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_REPRESENTANTES';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_AUTORES';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_OBRAS';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_CALENDARIO';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_PAGOS';           EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================
-- CREACION DE SECUENCIAS
-- ============================================================

CREATE SEQUENCE CASJ_SEQ_PAISES
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE CASJ_SEQ_CIUDADES
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE CASJ_SEQ_INSTITUCIONES
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE CASJ_SEQ_CLUB_LECTOR
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- CASJ_SEQ_CLUB_LECTOR es la fuente primaria de IDs para Clubes y Miembros
-- ya que ambos heredan del supertipo CLUB_LECTOR

CREATE SEQUENCE CASJ_SEQ_IDIOMAS
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE CASJ_SEQ_GRUPOS
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE CASJ_SEQ_REPRESENTANTES
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE CASJ_SEQ_AUTORES
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE CASJ_SEQ_OBRAS
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE CASJ_SEQ_CALENDARIO
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE CASJ_SEQ_PAGOS
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-- ============================================================
-- VERIFICACION
-- ============================================================
SELECT sequence_name, min_value, max_value, increment_by
FROM user_sequences
WHERE sequence_name LIKE 'CASJ_%'
ORDER BY sequence_name;
