-- ============================================================
-- CLUBES DE LECTURA - BASE DE DATOS TRANSACCIONAL
-- Archivo: 01_secuencias.sql
-- Descripcion: Creacion de todas las secuencias
-- Prefijo: CASJ_
-- MBD: Oracle
-- ============================================================

-- ============================================================
-- LIMPIEZA PREVIA (DROP si existen)
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE casj_seq_paises';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE casj_seq_ciudades';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE casj_seq_instituciones';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE casj_seq_clubes';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE casj_seq_idiomas';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE casj_seq_representantes';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE casj_seq_miembros';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE casj_seq_idioma_lector';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE casj_seq_pago_membresia';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE casj_seq_autores';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE casj_seq_obras';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- Limpiar secuencias del esquema anterior si existieran
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_PAISES';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_CIUDADES';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_INSTITUCIONES';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_CLUB_LECTOR';     EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_IDIOMAS';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_GRUPOS';          EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_REPRESENTANTES';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_AUTORES';         EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_OBRAS';           EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_CALENDARIO';      EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CASJ_SEQ_PAGOS';           EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ============================================================
-- CREACION DE SECUENCIAS
-- ============================================================

CREATE SEQUENCE casj_seq_paises         START WITH 10 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE casj_seq_ciudades       START WITH 10 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE casj_seq_instituciones  START WITH 5 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE casj_seq_clubes         START WITH 9 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE casj_seq_idiomas        START WITH 8 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE casj_seq_representantes START WITH 10 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE casj_seq_miembros       START WITH 97 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE casj_seq_idioma_lector  START WITH 117 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE casj_seq_pago_membresia START WITH 73 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE casj_seq_autores        START WITH 16 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE casj_seq_obras          START WITH 9 INCREMENT BY 1 NOCACHE;

-- ============================================================
-- VERIFICACION
-- ============================================================
SELECT sequence_name, min_value, max_value, increment_by
FROM user_sequences
WHERE UPPER(sequence_name) LIKE 'CASJ_%'
ORDER BY sequence_name;
