-- ============================================================
-- CLUBES DE LECTURA - BASE DE DATOS TRANSACCIONAL (NUEVO MODELO)
-- Archivo: 07_seguridad.sql
-- Descripcion: Propuesta de seguridad logica adaptada al nuevo ER
-- Prefijo: CASJ_
-- ============================================================

-- ============================================================
-- 1. CREACION DE ROLES
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP ROLE CASJ_ROL_ADMIN';        EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE CASJ_ROL_COORDINADOR';  EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE CASJ_ROL_SECRETARIO';   EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE CASJ_ROL_CONSULTOR';    EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP ROLE CASJ_ROL_AUDITOR';      EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE ROLE CASJ_ROL_ADMIN;
CREATE ROLE CASJ_ROL_COORDINADOR;
CREATE ROLE CASJ_ROL_SECRETARIO;
CREATE ROLE CASJ_ROL_CONSULTOR;
CREATE ROLE CASJ_ROL_AUDITOR;

-- ============================================================
-- 2. ASIGNACION DE PRIVILEGIOS A ROLES
-- ============================================================

-- -----------------------------------------------------------
-- CASJ_ROL_ADMIN: Todos los privilegios
-- -----------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_PAIS TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_CIUDAD TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_INSTITUCION TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_CLUB_LECTOR TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_CLUB TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_ASOCIADOS TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_IDIOMA TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_IDIOMA_CLUB_LECTOR TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_REPRESENTANTE TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_MIEMBRO TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_MIEMBRO_NACIONALIDAD TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_GRUPO_LECTURA TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_ASIGNACION TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_HISTORICO_MEMBRESIA TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_PAGO_MEMBRESIA TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_LIBRO TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_AUTOR TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_LIBRO_AUTOR TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_PREFERENCIA_MIEMBRO TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_OBRA TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_LIBRO_OBRA TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_ELENCO TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_PRESENTACION TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_MEJOR_ACTOR TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_CALENDARIO_REUNION_MES TO CASJ_ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CASJ_INASISTENCIA TO CASJ_ROL_ADMIN;

-- Vistas
GRANT SELECT ON CASJ_VW_FICHA_MIEMBRO TO CASJ_ROL_ADMIN;
GRANT SELECT ON CASJ_VW_HISTORIAL_MIEMBRO TO CASJ_ROL_ADMIN;
GRANT SELECT ON CASJ_VW_FICHA_CLUB TO CASJ_ROL_ADMIN;
GRANT SELECT ON CASJ_VW_FICHA_LIBRO TO CASJ_ROL_ADMIN;
GRANT SELECT ON CASJ_VW_LIBROS_VALORADOS TO CASJ_ROL_ADMIN;
GRANT SELECT ON CASJ_VW_MIEMBROS_ACTIVOS TO CASJ_ROL_ADMIN;
GRANT SELECT ON CASJ_VW_ASISTENCIA_BIMESTRE TO CASJ_ROL_ADMIN;
GRANT SELECT ON CASJ_VW_ORDEN_LECTURA TO CASJ_ROL_ADMIN;
GRANT SELECT ON CASJ_VW_PAISES_MONEDAS TO CASJ_ROL_ADMIN;

-- Funciones y Procedimientos
GRANT EXECUTE ON CASJ_FN_CONVERSION_MONETARIA TO CASJ_ROL_ADMIN;
GRANT EXECUTE ON CASJ_FN_EDAD_MIEMBRO TO CASJ_ROL_ADMIN;
GRANT EXECUTE ON CASJ_FN_ANTIGUEDAD_CLUB_MIEMBRO TO CASJ_ROL_ADMIN;
GRANT EXECUTE ON CASJ_FN_PROM_PARTICIPACION_MENSUAL TO CASJ_ROL_ADMIN;
GRANT EXECUTE ON CASJ_FN_PARTICIPACION_BIMESTRE_MIEMBRO TO CASJ_ROL_ADMIN;
GRANT EXECUTE ON CASJ_SP_CONVERTIR_MONEDA TO CASJ_ROL_ADMIN;
GRANT EXECUTE ON CASJ_SP_INFO_MIEMBRO TO CASJ_ROL_ADMIN;
GRANT EXECUTE ON CASJ_SP_PARTICIPACION_MENSUAL TO CASJ_ROL_ADMIN;
GRANT EXECUTE ON CASJ_SP_PARTICIPACION_BIMESTRE TO CASJ_ROL_ADMIN;

-- -----------------------------------------------------------
-- CASJ_ROL_COORDINADOR
-- -----------------------------------------------------------
GRANT SELECT ON CASJ_CLUB TO CASJ_ROL_COORDINADOR;
GRANT SELECT ON CASJ_MIEMBRO TO CASJ_ROL_COORDINADOR;
GRANT SELECT ON CASJ_GRUPO_LECTURA TO CASJ_ROL_COORDINADOR;
GRANT SELECT ON CASJ_ASIGNACION TO CASJ_ROL_COORDINADOR;
GRANT SELECT ON CASJ_LIBRO TO CASJ_ROL_COORDINADOR;

GRANT SELECT, INSERT, UPDATE ON CASJ_CALENDARIO_REUNION_MES TO CASJ_ROL_COORDINADOR;
GRANT SELECT, INSERT, UPDATE ON CASJ_INASISTENCIA TO CASJ_ROL_COORDINADOR;

GRANT SELECT ON CASJ_VW_MIEMBROS_ACTIVOS TO CASJ_ROL_COORDINADOR;
GRANT SELECT ON CASJ_VW_ASISTENCIA_BIMESTRE TO CASJ_ROL_COORDINADOR;

GRANT EXECUTE ON CASJ_FN_PROM_PARTICIPACION_MENSUAL TO CASJ_ROL_COORDINADOR;
GRANT EXECUTE ON CASJ_FN_PARTICIPACION_BIMESTRE_MIEMBRO TO CASJ_ROL_COORDINADOR;
GRANT EXECUTE ON CASJ_SP_PARTICIPACION_MENSUAL TO CASJ_ROL_COORDINADOR;
GRANT EXECUTE ON CASJ_SP_PARTICIPACION_BIMESTRE TO CASJ_ROL_COORDINADOR;

-- -----------------------------------------------------------
-- CASJ_ROL_SECRETARIO
-- -----------------------------------------------------------
GRANT SELECT ON CASJ_CLUB TO CASJ_ROL_SECRETARIO;
GRANT SELECT ON CASJ_PAIS TO CASJ_ROL_SECRETARIO;
GRANT SELECT ON CASJ_IDIOMA TO CASJ_ROL_SECRETARIO;

GRANT SELECT, INSERT, UPDATE ON CASJ_CLUB_LECTOR TO CASJ_ROL_SECRETARIO;
GRANT SELECT, INSERT, UPDATE ON CASJ_MIEMBRO TO CASJ_ROL_SECRETARIO;
GRANT SELECT, INSERT, UPDATE ON CASJ_REPRESENTANTE TO CASJ_ROL_SECRETARIO;
GRANT SELECT, INSERT, UPDATE ON CASJ_HISTORICO_MEMBRESIA TO CASJ_ROL_SECRETARIO;
GRANT SELECT, INSERT, UPDATE ON CASJ_PAGO_MEMBRESIA TO CASJ_ROL_SECRETARIO;
GRANT SELECT, INSERT, UPDATE ON CASJ_ASIGNACION TO CASJ_ROL_SECRETARIO;

GRANT SELECT ON CASJ_VW_FICHA_MIEMBRO TO CASJ_ROL_SECRETARIO;
GRANT SELECT ON CASJ_VW_HISTORIAL_MIEMBRO TO CASJ_ROL_SECRETARIO;

GRANT EXECUTE ON CASJ_FN_CONVERSION_MONETARIA TO CASJ_ROL_SECRETARIO;
GRANT EXECUTE ON CASJ_FN_EDAD_MIEMBRO TO CASJ_ROL_SECRETARIO;
GRANT EXECUTE ON CASJ_FN_ANTIGUEDAD_CLUB_MIEMBRO TO CASJ_ROL_SECRETARIO;
GRANT EXECUTE ON CASJ_SP_CONVERTIR_MONEDA TO CASJ_ROL_SECRETARIO;
GRANT EXECUTE ON CASJ_SP_INFO_MIEMBRO TO CASJ_ROL_SECRETARIO;

-- -----------------------------------------------------------
-- CASJ_ROL_CONSULTOR & CASJ_ROL_AUDITOR
-- -----------------------------------------------------------
GRANT SELECT ON CASJ_VW_FICHA_CLUB TO CASJ_ROL_CONSULTOR;
GRANT SELECT ON CASJ_VW_FICHA_LIBRO TO CASJ_ROL_CONSULTOR;
GRANT SELECT ON CASJ_VW_PAISES_MONEDAS TO CASJ_ROL_CONSULTOR;

GRANT SELECT ON CASJ_MIEMBRO TO CASJ_ROL_AUDITOR;
GRANT SELECT ON CASJ_CLUB TO CASJ_ROL_AUDITOR;
GRANT SELECT ON CASJ_PAGO_MEMBRESIA TO CASJ_ROL_AUDITOR;

-- ============================================================
-- 3. PERFILES DE CONEXION
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP PROFILE CASJ_PERFIL_ADMIN'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE PROFILE CASJ_PERFIL_ADMIN LIMIT SESSIONS_PER_USER 3 IDLE_TIME 60;

-- ============================================================
-- 4. USUARIOS
-- ============================================================
BEGIN EXECUTE IMMEDIATE 'DROP USER CASJ_ADMIN CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE USER CASJ_ADMIN IDENTIFIED BY Admin2026$ PROFILE CASJ_PERFIL_ADMIN ACCOUNT UNLOCK;
GRANT CREATE SESSION TO CASJ_ADMIN;
GRANT CASJ_ROL_ADMIN TO CASJ_ADMIN;

-- ============================================================
-- 5. AUDITORIA BASICA
-- ============================================================
AUDIT INSERT, UPDATE, DELETE ON CASJ_MIEMBRO BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON CASJ_PAGO_MEMBRESIA BY ACCESS;
AUDIT INSERT, UPDATE, DELETE ON CASJ_HISTORICO_MEMBRESIA BY ACCESS;
AUDIT CREATE SESSION WHENEVER NOT SUCCESSFUL;

